name: Audit-Logs-Coralogix-Image

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - './Dockerfile'
      - './**.go'
      - './**.mod'
      - './**.sum'
      - '.github/workflows/image.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.5'
      - run: go test ./... -v
